# -*- coding: utf-8 -*-
"""
Plausibility check for the heatmaps generated by script 22.

Loads .npz files for a few sample images from the stress-test manifest,
visualizes each as a methods x models matrix overlaid on the input image,
and saves one figure per sample to results/figures/.

Note: the display image must match exactly what the model saw when the
heatmap was generated. timm models apply resize + center-crop (NOT a plain
square resize), and different models use different input sizes (ResNet50 /
ViT-B/16: 224, MobileViT-S: 256) and crop percentages. So each (sample,
model) cell gets its own display image, reproducing that model's resize+crop
pipeline minus the normalization step. Without this, heatmaps appear shifted
and distorted relative to the background image.

Uses the ground-truth target ('_gt' key in the .npz).
"""

import sys
import csv
import random
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.paths import PROJECT_ROOT, DATA_DIR, RESULTS_DIR, FIGURES_DIR
from src.models import load_model

import numpy as np
import torch
import timm
import matplotlib.pyplot as plt
from PIL import Image
from torchvision import transforms as T

# --- 1. Configuration ---
MANIFEST_NAME = "subset_50x1_seed42.csv"
N_SAMPLES_TO_INSPECT = 3
SEED = 0  # selection seed. Independent of the manifest's own seed

MANIFEST_PATH = DATA_DIR / "manifests" / MANIFEST_NAME
HEATMAPS_DIR = RESULTS_DIR / "heatmaps" / MANIFEST_PATH.stem

MODEL_NAMES = ["resnet50", "vit_base", "mobilevit_s"]
METHOD_NAMES = ["IntegratedGradients", "GradCAM", "Random", "LRP", "Chefer-LRP"]

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# --- 2. Pick samples to inspect ---
with open(MANIFEST_PATH, "r", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    manifest_rows = list(reader)

rng = random.Random(SEED)
chosen_rows = rng.sample(manifest_rows, N_SAMPLES_TO_INSPECT)
print(f"Inspecting {N_SAMPLES_TO_INSPECT} samples (selection seed {SEED}):")
for row in chosen_rows:
    print(f"  sample_id={row['sample_id']}, synset={row['synset_id']}, "
          f"class_idx={row['class_idx']}")

# --- 3. Per-model display transforms (resize + crop, NO normalization) ---
# Build one display pipeline per model, mimicking timm's preprocessing up
# to (but not including) Normalize. We cache them so we don't rebuild per
# image. Also cache each model's input size for overlay alignment.
display_transforms = {}
input_sizes = {}
for model_name in MODEL_NAMES:
    bundle = load_model(model_name, device)
    cfg = timm.data.resolve_model_data_config(bundle.model)
    input_size = cfg["input_size"][-1]            # e.g. 224 or 256
    crop_pct = cfg.get("crop_pct", 0.875)
    resize_size = int(round(input_size / crop_pct))
    display_transforms[model_name] = T.Compose([
        T.Resize(resize_size, interpolation=T.InterpolationMode.BICUBIC),
        T.CenterCrop(input_size),
    ])
    input_sizes[model_name] = input_size
    # We only needed the config. Free the model immediately.
    del bundle
    if device.type == "cuda":
        torch.cuda.empty_cache()

def get_display_image(img_rel_path: str, model_name: str) -> np.ndarray:
    """
    Reproduce the model's resize+crop (no normalization) and return a
    float array in [0, 1] for matplotlib. Matches the spatial framing the
    model saw, so heatmap overlays align.
    """
    img = Image.open(PROJECT_ROOT / img_rel_path).convert("RGB")
    img = display_transforms[model_name](img)
    return np.asarray(img).astype(np.float32) / 255.0

# --- 4. Load heatmaps for one (sample, model) ---
def load_heatmaps(sample_id: int, model_name: str) -> dict:
    """Return {method_name: heatmap or None} for all METHOD_NAMES."""
    npz_path = HEATMAPS_DIR / f"sample_{sample_id:05d}_{model_name}.npz"
    if not npz_path.exists():
        raise FileNotFoundError(f"Missing: {npz_path}")
    with np.load(npz_path) as data:
        present = set(data.files)
        return {
            m: (data[f"{m}_gt"].copy() if f"{m}_gt" in present else None)
            for m in METHOD_NAMES
        }

# --- 5. One figure per sample ---
for row in chosen_rows:
    sample_id = int(row["sample_id"])
    synset_id = row["synset_id"]
    class_idx = int(row["class_idx"])

    # Pre-load display images and heatmaps per model
    display_imgs = {m: get_display_image(row["image_path"], m) for m in MODEL_NAMES}
    results = {m: load_heatmaps(sample_id, m) for m in MODEL_NAMES}

    n_rows = len(METHOD_NAMES)
    n_cols = len(MODEL_NAMES)
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(5 * n_cols, 5 * n_rows))

    for r, method_name in enumerate(METHOD_NAMES):
        for c, model_name in enumerate(MODEL_NAMES):
            ax = axes[r, c]
            heatmap = results[model_name][method_name]
            img_display = display_imgs[model_name]

            if heatmap is not None:
                # Heatmap and display image are now both in the model's
                # native input size (e.g. 256 for MobileViT), so they
                # align without rescaling. If shapes still differ (safety),
                # let imshow's extent match the image.
                ax.imshow(img_display)
                ax.imshow(
                    heatmap, cmap="hot", alpha=0.5,
                    extent=(0, img_display.shape[1], img_display.shape[0], 0),
                )
            else:
                ax.set_facecolor("#2a2a2a")
                ax.text(0.5, 0.5, "n/a", transform=ax.transAxes,
                        ha="center", va="center", fontsize=20, color="#aaaaaa")

            ax.set_xticks([])
            ax.set_yticks([])
            if r == 0:
                ax.set_title(model_name, fontsize=14)
            if c == 0:
                ax.text(-0.1, 0.5, method_name, transform=ax.transAxes,
                        fontsize=12, rotation=90, va="center", ha="center")

    fig.suptitle(
        f"sample_id={sample_id}  synset={synset_id}  class_idx={class_idx}",
        fontsize=14,
    )
    plt.tight_layout(rect=[0, 0, 1, 0.97])

    out_path = FIGURES_DIR / f"25_stresstest_validation_sample_{sample_id:05d}.png"
    plt.savefig(out_path, dpi=120, bbox_inches="tight")
    print(f"Saved: {out_path}")
    plt.show()
    