# -*- coding: utf-8 -*-
"""
Compute per-model classification accuracy and misclassification overlap
on the manifest subset.

Reads class_idx_gt and class_idx_pred from the heatmap .npz files
generated by script 22 and produces a small table summarizing:
  - per-model accuracy (correct, misclassified, percentages)
  - overlap structure ("any model wrong", "all models wrong")

Output:
    results/tables/classification_accuracy__<manifest_stem>.parquet
"""

import sys
import re
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.paths import RESULTS_DIR, TABLES_DIR

import numpy as np
import pandas as pd

# --- 1. Configuration ---
MANIFEST_STEM = "subset_500x2_seed42"
HEATMAPS_DIR  = RESULTS_DIR / "heatmaps" / MANIFEST_STEM
OUTPUT_PATH   = TABLES_DIR / f"classification_accuracy__{MANIFEST_STEM}.parquet"

MODEL_NAMES = ["resnet50", "vit_base", "mobilevit_s"]

# --- 2. Read misclassified sample IDs per model from .npz metadata ---
print(f"Reading classification outcomes from: {HEATMAPS_DIR}")

misclass_per_model = {}
for model in MODEL_NAMES:
    misclassified = set()
    files = sorted(HEATMAPS_DIR.glob(f"sample_*_{model}.npz"))
    for f in files:
        with np.load(f) as data:
            if int(data["class_idx_gt"]) != int(data["class_idx_pred"]):
                sid = int(re.match(r"sample_(\d+)_", f.name).group(1))
                misclassified.add(sid)
    misclass_per_model[model] = misclassified

# Total samples in the manifest (we assume the heatmap dir is complete).
# Use one model's .npz count as the reference. All three should have the
# same total since script 22 processes the full manifest per model.
total_samples = len(sorted(HEATMAPS_DIR.glob(f"sample_*_{MODEL_NAMES[0]}.npz")))
print(f"  total samples: {total_samples}")

# --- 3. Per-model accuracy ---
rows = []
for model in MODEL_NAMES:
    n_mis = len(misclass_per_model[model])
    n_cor = total_samples - n_mis
    rows.append({
        "category": "per_model",
        "label": model,
        "n_correct": n_cor,
        "n_misclassified": n_mis,
        "pct_correct": 100 * n_cor / total_samples,
        "pct_misclassified": 100 * n_mis / total_samples,
    })

# --- 4. Overlap structure ---
# "any_model_wrong" = union (at least one model misclassified this sample)
# "all_models_wrong" = intersection (every model misclassified this sample)
misclass_any = (misclass_per_model["resnet50"]
                | misclass_per_model["vit_base"]
                | misclass_per_model["mobilevit_s"])
misclass_all = (misclass_per_model["resnet50"]
                & misclass_per_model["vit_base"]
                & misclass_per_model["mobilevit_s"])

rows.append({
    "category": "overlap",
    "label": "any_model_wrong",
    "n_correct": total_samples - len(misclass_any),
    "n_misclassified": len(misclass_any),
    "pct_correct": 100 * (total_samples - len(misclass_any)) / total_samples,
    "pct_misclassified": 100 * len(misclass_any) / total_samples,
})
rows.append({
    "category": "overlap",
    "label": "all_models_wrong",
    "n_correct": total_samples - len(misclass_all),
    "n_misclassified": len(misclass_all),
    "pct_correct": 100 * (total_samples - len(misclass_all)) / total_samples,
    "pct_misclassified": 100 * len(misclass_all) / total_samples,
})

# --- 5. Save and preview ---
df = pd.DataFrame(rows)
print(f"\nSaving accuracy table to: {OUTPUT_PATH}")
df.to_parquet(OUTPUT_PATH, index=False)
print(f"  size: {OUTPUT_PATH.stat().st_size / 1024:.1f} KB")

print("\n--- Preview ---")
print(df.to_string(index=False))